In [2]:
import numpy as np

In [2]:
# Criar uma matriz UNIdimensional
matriz_unidimensional = np.array([11,12,13,14,15])
print(matriz_unidimensional)
print(type(matriz_unidimensional))

[11 12 13 14 15]
<class 'numpy.ndarray'>


In [5]:
# Criar array com um tipo específico
array_float64_1 = np.array([11,12,13,14,15], dtype=np.float64)
print(array_float64_1)
print(type(array_float64_1))
# OU
array_float64_2 = np.array([11.0,12.0,13.0,14.0,15.0])
print(array_float64_2)
print(type(array_float64_2))
# E
array_int32 = np.array([11,12,13,14,15], dtype=np.int32)
print(array_int32)
print(type(array_int32))

[11. 12. 13. 14. 15.]
<class 'numpy.ndarray'>
[11. 12. 13. 14. 15.]
<class 'numpy.ndarray'>
[11 12 13 14 15]
<class 'numpy.ndarray'>


In [10]:
# MUDAR tipo de array
array_mudado = np.array([11,12,13,14,15])
print(array_mudado)
print(type(array_mudado))

array_mudado = array_mudado.astype(np.float64)
print(array_mudado)
print(type(array_mudado))

# O inverso também
array_mudado_2 = np.array([11.1, 12.5, 13.8, 14.9, 15.1])
print(array_mudado_2)
array_mudado_2 = array_mudado_2.astype(np.int32)
print(array_mudado_2)

[11 12 13 14 15]
<class 'numpy.ndarray'>
[11. 12. 13. 14. 15.]
<class 'numpy.ndarray'>
[11.1 12.5 13.8 14.9 15.1]
[11 12 13 14 15]


In [11]:
# Matriz MULTIdimensional

# BIdimensional 
matriz_multidimensional = np.array([[11,12],[13,14],[15,16]])
print(matriz_multidimensional)

[[11 12]
 [13 14]
 [15 16]]


In [20]:
# Arrays vazios tipificados

#emptys não inicializados
vazio = np.empty([3,3], dtype=np.int32)
print(vazio)

print('-'*20)

# Matriz de zeros
zeros = np.zeros([4,3], dtype=np.int32)
print(zeros)

print('-'*20)

# Matriz de uns
ones = np.ones([5,2], dtype=np.float64)
print(ones)

print('-'*20)

# Matriz de zeros com diagonal de uns
diagonal = np.eye(5)
print(diagonal)

[[        0         0 989700528]
 [    32760         1         0]
 [       -1        -1         0]]
--------------------
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
--------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
--------------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
# Valores aleatórios ENTRE 0 E 1.
aleatorio = np.random.random((5))
print(aleatorio)

print('='*60)

# Valores aleatórios em distribuição nomral contendo negativos
aleatorio_2 = np.random.randn((5))
print(aleatorio_2)

print('='*60)

# valores aletórios 3x4
aleatorio_3 = 10*(np.random.random((3,4)))
print(aleatorio_3)

[0.19725863 0.40513187 0.86680906 0.60736429 0.22537175]
[ 1.26647679  0.17250189 -0.24478986 -0.54817565  0.96803586]
[[5.91243855 5.33185179 2.53126208 7.68864922]
 [6.74672905 3.18168864 8.87846109 7.18743531]
 [5.68025488 2.68530881 3.29466376 0.8414333 ]]


In [38]:
# Outras formas de gerar valores:

# SEMENTES
seed = np.random.default_rng(4)
aleatorio_5 = seed.random(3)
print(aleatorio_5)

# gerar inteiros
print("\n\nSUDOKU")
aleatorio_6 = seed.integers(10, size=(9,9))
print(aleatorio_6)


[0.94305611 0.51132755 0.97624371]


SUDOKU
[[9 0 4 6 2 3 6 8 5]
 [1 6 8 2 5 3 9 0 4]
 [8 4 1 7 9 9 9 3 7]
 [9 5 9 5 1 4 6 3 7]
 [4 9 2 6 0 1 5 4 4]
 [4 8 5 3 9 8 3 2 2]
 [1 5 5 6 8 9 5 5 0]
 [2 9 9 0 4 4 6 1 4]
 [3 2 8 6 1 7 5 1 6]]


In [40]:
# Remover repetições

z = np.array([11,12,13,12,14,15,13,15,16,11])
print(z)

z = np.unique(z)
print(z)

[11 12 13 12 14 15 13 15 16 11]
[11 12 13 14 15 16]


In [43]:
# Funcões específicas

# Gerar matriz BIdimensional
k = np.array([[11,12,13],[14,15,16],[17,18,19]])
print(k)

# Mostrar elementos específicos
print(k[2][0])

# Mostrar tamanho:
print(k.shape)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
17
(3, 3)


In [44]:
# Funções matemáticas

print(k.max()) # Valor máximo
print(k.min()) # Valor mínimo
print(k.mean()) # Média
print(k.sum()) # Soma dos valores
print(k.std()) # Desvio padrão dos valores


19
11
15.0
135
2.581988897471611


In [50]:
# Funções universais, aplicadas  a todos os elementos

# Raiz qudrada
q = np.array([1,4,9,16,25,36,49])
print(q)
q = np.sqrt(q)
print(q)

print('='*60)
# Valor exponencial:
e = np.array([1,2,3,4,5,6])
print(e)
e = np.exp(e)
print(e)

[ 1  4  9 16 25 36 49]
[1. 2. 3. 4. 5. 6. 7.]
[1 2 3 4 5 6]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [7]:
# extração de elementos

extracao = np.array([1,2,3,4,5,6,7,8,9])

# Extrair elemento na posiçao 2
print(extracao[2])

# Extrair do elemento 0 ao 2
print(extracao[0:2])

# Extrair elementos a partir da posição 2
print(extracao[2:])

# Extrair valor da -3ª posição até a última
print(extracao[-3:])

3
[1 2]
[3 4 5 6 7 8 9]
[7 8 9]


In [12]:
# Extração de linhas e colunas

extracao_2 = np.array([[11,12,13],[14,15,16],[17,18,19]])

# Primeira linhas, todas as colunas
print(extracao_2[0, :])

# Segunda linha
print(extracao_2[1, :])

# Terceira linha
print(extracao_2[2])

# Todas as linhas, primeira coluna
print(extracao_2[:, 0])

# Todas as linhas, segunda coluna
print(extracao_2[:,1])

# Todas as linhas, terceira coluna
print(extracao_2[:,2])

[11 12 13]
[14 15 16]
[17 18 19]
[11 14 17]
[12 15 18]
[13 16 19]


In [17]:
# Adição e multiplicação de matrizes

a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

# Adição
print(a+b)

print('='*20)
# Multiplicação
print(a*b)

[[2 4]
 [6 8]]
[[ 1  4]
 [ 9 16]]


In [32]:
# Transposição e rearranjo

f = np.arange(15)
print(f)
print('='*60)

# Rearranjo
f = f.reshape((3,5))
print(f)
print('='*60)

# Transposição
f2= f.T
print(f2)
# OU
print('OU')
f2 = f.transpose((1,0))
print(f2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
OU
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [35]:
# Expressões lógicas

# Usando where
g = np.arange(15).reshape((3,5)) # Criando matriz
print(g)
print('='*60)

g1 = (g > 10) # Posições maiores que 10
print(g1)
print('='*60)

g2 = np.where(g>10, 1, -1)
print(g2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1  1  1  1  1]]
